server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${FIN_TRADE_X_RDB_URL}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${FIN_TRADE_X_RDB_USERNAME}
    password: ${FIN_TRADE_X_RDB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect