name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Configure AWS Credentials
      # You may pin to the exact commit or the version.
      # uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        # AWS Region, e.g. us-east-2
        aws-region: us-east-1
        # AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        # AWS Secret Access Key. Required if aws-access-key-id is provided.
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Amazon ECR Login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: dev/find-trade-x-rep
        IMAGE_TAG: latest
      run: |
        docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" -f user/Dockerfile .
        docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
